### ISSUE TITLE
Will this work with Gerrit 2.12?

### ISSUE THREAD

**Issue by bdellegrazie** [davido/gerrit-oauth-provider#54]
Hi will the current version of this plugin work with Gerrit 2.12.x or does it need modification?

Thanks!

**Comment by davido** [comment]
There wasn' any API changes in this area, so that the plugin should work as is. However, there was a serious bug in Gerrit core, that got fixed in: [1], but wasn't released yet. It's only relate to linking of existing (and non-existing) Google OpenID accounts.

* [1] https://gerrit-review.googlesource.com/#/c/73160/
